server {
    listen       80;
    server_name  localhost;

    # 后端 API 转发（去掉 /api/mall 前缀 -> 后端 /v1/...）
    # 172.17.0.1 是宿主机 docker 网桥默认 IP，用于从 bridge 容器访问宿主机端口
    location /api/mall {
        proxy_pass         http://172.17.0.1:8560/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    # 后端 API 转发（去掉 /api/admin 前缀）
    location /api/admin {
        proxy_pass         http://172.17.0.1:8560/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    # 后端 API 转发（去掉 /api/v1 前缀）
    location /api/v1 {
        proxy_pass         http://172.17.0.1:8560/;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}
